repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-alloy
    chart: grafana/alloy
    version: 1.5.3
    namespace: grafana-alloy
    values:
      - values.yaml
