repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-loki
    chart: grafana/loki
    version: 6.52.0
    namespace: grafana-loki
    atomic: true
    values:
      - values.yaml
