repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 28.6.1
    namespace: prometheus
    atomic: true
    values:
      - values.yaml
