repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    chart: grafana/grafana
    version: 10.4.3
    namespace: grafana
    atomic: true
    values:
      - values.yaml
